import type { Metadata, Viewport } from "next";
import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { PostHogPageView } from "@/components/providers/PostHogPageView";
import { CookieConsent } from "@/components/shared/CookieConsent";
import { AttributionTracker } from "@/components/shared/AttributionTracker";
import { JourneyTracker } from "@/components/shared/JourneyTracker";
import { ClarityAnalytics } from "@/components/shared/ClarityAnalytics";
import { SOCIAL_LINKS } from "@/lib/constants";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://buildpm.co"),
  title: {
    default: "BuildPM: The Future of Building for Product Managers",
    template: "%s | BuildPM",
  },
  description:
    "A community for PMs who build and ship. Free enterprise tools, build squads, career growth. Not another Slack group.",
  keywords: [
    "product management",
    "PM community",
    "build in public",
    "AI product management",
    "product manager tools",
    "ship products",
    "PM career",
    "builder community",
  ],
  authors: [{ name: "BuildPM" }],
  creator: "BuildPM",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://buildpm.co",
    siteName: "BuildPM",
    title: "BuildPM: The Future of Building for Product Managers",
    description:
      "Free enterprise tools. Build squads. Career growth. A community for PMs who build, not just talk.",
    // og:image is generated by app/opengraph-image.tsx (no static file needed).
  },
  twitter: {
    card: "summary_large_image",
    title: "BuildPM: The Future of Building for Product Managers",
    description:
      "Free enterprise tools. Build squads. Career growth. A community for PMs who build, not just talk.",
    // twitter:image is generated by app/twitter-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

// Mobile viewport: device-width, zoom NOT disabled (a11y), cover the notch for
// safe-area insets, and a theme-color that tracks light/dark.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F7F6F3" },
    { media: "(prefers-color-scheme: dark)", color: "#1A1A1A" },
  ],
};

// Auto-populates as you uncomment social profiles in lib/constants.ts.
const sameAs = SOCIAL_LINKS.map((s) => s.href);

const structuredData = JSON.stringify({
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://buildpm.co/#organization",
      name: "BuildPM",
      url: "https://buildpm.co",
      logo: "https://buildpm.co/icon",
      description:
        "A community for product managers who build and ship real products. Free enterprise tools, build squads, and career growth.",
      foundingDate: "2026",
      ...(sameAs.length ? { sameAs } : {}),
    },
    {
      "@type": "WebSite",
      "@id": "https://buildpm.co/#website",
      name: "BuildPM",
      url: "https://buildpm.co",
      description:
        "BuildPM: the future of building for product managers. Build real products, prove your work, and get hired.",
      publisher: { "@id": "https://buildpm.co/#organization" },
      inLanguage: "en",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          type="application/ld+json"
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: structuredData }}
        />
      </head>
      <body className="bg-background text-foreground font-body antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[200] focus:px-4 focus:py-2 focus:bg-accent focus:text-accent-foreground focus:rounded-lg focus:text-sm focus:font-medium"
          >
            Skip to content
          </a>
          {children}
          <Suspense>
            <PostHogPageView />
          </Suspense>
          <CookieConsent />
          <ClarityAnalytics />
          <AttributionTracker />
          <Suspense>
            <JourneyTracker />
          </Suspense>
          <Analytics />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
